#!/usr/bin/env python
import sys
import numpy as np

def pareto_frontier2(lst):
    myList = sorted(lst, reverse=True)
    p_front = [myList[0]]
    for pair in myList[1:]:
        if pair[1] > p_front[-1][1]:
            p_front.append(pair)
    return p_front


c = [int(n) for n in sys.argv[1:-1]]
fn = sys.argv[-1]

dat = []
for idx,line in enumerate(open(fn).readlines()):
	s = line.split()
	v = [float(s[i]) for i in c] + [line]
	dat.append(v)

for p in pareto_frontier2(dat):
	print p[-1],
